config/routes.rb
LandingAgroSocial::Application.routes.draw do
  get "agro_social/index"
  post "agro_social/save_mailer"
  root :to => "agro_social#index"

  

end

app/models/mail.rb
class Mail < ActiveRecord::Base
end

app/models/users.rb
class Users < ActiveRecord::Base
end

app/controllers/agro_social_controller.rb
class AgroSocialController < ApplicationController
  def index
  	@users = Users.order(name: :asc)
  	@mail = Mail.new
  end

  def save_mailer
  	@mail = Mail.new(params.require(:mail).permit(:mail))
  	if @mail.save
  		flash[:message] = "Obrigado pela subscrição! Tenha uma bom dia"
  	end
  	redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agro_social_helper.rb
module AgroSocialHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agro_social/index.html.erb
<!-- Side Menu -->
<a id="menu-toggle" href="#" class="btn btn-lg toggle"><i id="icon-menu-toggle" class="icon-reorder"></i></a>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <button type="button" id="menu-close" class="close pull-right toogle position">&times</button>
    <li class="sidebar-brand"><a href="http://agrosocial.pt" target="_blank">AgroSocial</a></li>
    <hr>
    <li><a href="#top">Início</a></li>
    <li><a href="#services">O Que Fazemos</a></li>
    <li><a href="#team">Quem Somos</a></li>
  </ul>
</div>
<!-- /Side Menu -->

<!-- Full Page Image Header Area -->
<div id="top" class="header">
  <div class="vert-text">
    <h1>AgroSocial</h1>
    <br>
    <h3>A semente do seu negócio</h3>
    <br>
    <ul class="list-inline">
      <li><a href="https://www.facebook.com/386752774760741" target="_blank"><div id="facebook"></div></a></li>
      <li><a href="https://plus.google.com/106344021008787626515/posts" target="_blank"><div id="gplus"></div></a></li>
      <li><a href="https://twitter.com/agro_social" target="_blank"><div id="twitter"></div></a></li>
      <li><a href="https://agrosocial.pt" target="_blank"><div id="contact"></div></a></li>
    </ul>

    <div id="mail-form">
     <p class="title">Receba as nossas novidades</p>
     <%= form_for @mail, :url => agro_social_save_mailer_path do |f| %>
     <%= f.text_field :mail, :class => "form-control", :placeholder => "Deixe o seu email", :autocomplete => :off %>
     <%= f.submit 'Subscrever', :class => "btn btn-primary" %>
     <% end %>
   </div>

   <div id="copyright">AgroSocial&copy 2013</div>
 </div>
</div>
<!-- /Full Page Image Header Area -->

<!-- Services -->
<div id="services" class="services">
  <div class="container">
    <div class="vert-text">
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <h2>O que fazemos</h2>
          <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 col-md-offset-1 text-center">
          <div class="service-item">
            <a class="frame" data-fancybox-type="iframe" href="http://www.youtube.com/embed/RetFcjbzInY?autoplay=1">
              <i class="service-icon icon-shopping-cart"></i>
            </a>
            <h4>Negócio</h4>
            <p>Encontre o melhor preço para o produto que procura ou divulgue os seus produtos a uma vasta comunidade.</p>
          </div>
        </div>
        <div class="col-md-2 text-center">
          <div class="service-item">
            <a class="frame" data-fancybox-type="iframe" href="http://www.youtube.com/embed/XMkeeZgHY14?autoplay=1">
              <i class="service-icon icon-male"></i>
            </a>
            <h4>Emprego</h4>
            <p>Encontre um emprego à medida das suas capacidades ou a mão de obra que precisa para aquela tarefa específica.</p>
          </div>
        </div>
        <div class="col-md-2 text-center">
          <div class="service-item">
            <a class="frame" data-fancybox-type="iframe" href="http://www.youtube.com/embed/yCn7XZVuRDg?autoplay=1">
              <i class="service-icon icon-group"></i>
            </a>
            <h4>Conhecimento</h4>
            <p>Participe em workshops ou siga técnicos especializados na nossa academia. Partilhe conhecimento na sua área de interesse.</p>
          </div>
        </div>
        <div class="col-md-2 text-center">
          <div class="service-item">
            <a class="frame" data-fancybox-type="iframe" href="http://www.youtube.com/embed/irLwbREnL54?autoplay=1">
              <i class="service-icon icon-bullhorn"></i>
            </a>
            <h4>Divulgação</h4>
            <p>Divulgue a sua empresa, negócio ou produtos facilmente e a quem realmente interessa.</p>
          </div>
        </div>
        <div class="col-md-2 text-center">
          <div class="service-item">
            <a class="frame" data-fancybox-type="iframe" href="http://www.youtube.com/embed/D5seyeETouQ?autoplay=1">
              <i class="service-icon icon-calendar-empty"></i>
            </a>
            <h4>Participação</h4>
            <p>Crie, promova e participe em eventos sociais ou profissionais.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Services -->

<!-- Team -->
<div id ="team" class="team">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 text-center">
        <h2>Quem somos</h2>
        <hr>
      </div>
    </div>
    <div class="row">
      <% @users.each_slice(6).each do |m| %>
      <div class="col-md-12 text-center">
        <ul>
          <% m.each do |member| %>
          <li><img src="/assets/team/<%= member.score_name %>.jpg" alt="<%= member.name %>" />
            <span><%= member.name %></span>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
</div>
<!-- /Team -->

<script type="text/javascript">
  $("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
  });
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
  });

  $(function() {
    $(document).click(function(event){
      var status = $(event.target);
      if(status.attr('id') != 'menu-toggle' && status.attr('id') != 'icon-menu-toggle') {
        $('#sidebar-wrapper').removeClass('active');
      }
    });

    $(".icon-shopping-cart").hover((function() {
      $(this).removeClass("icon-shopping-cart");
      return $(this).addClass("icon-play-circle");
    }), function() {
      $(this).removeClass("icon-play-circle");
      return $(this).addClass("icon-shopping-cart");
    });

    $(".icon-male").hover((function() {
      $(this).removeClass("icon-male");
      return $(this).addClass("icon-play-circle");
    }), function() {
      $(this).removeClass("icon-play-circle");
      return $(this).addClass("icon-male");
    });

    $(".icon-group").hover((function() {
      $(this).removeClass("icon-group");
      return $(this).addClass("icon-play-circle");
    }), function() {
      $(this).removeClass("icon-play-circle");
      return $(this).addClass("icon-group");
    });

    $(".icon-bullhorn").hover((function() {
      $(this).removeClass("icon-bullhorn");
      return $(this).addClass("icon-play-circle");
    }), function() {
      $(this).removeClass("icon-play-circle");
      return $(this).addClass("icon-bullhorn");
    });

    $(".icon-calendar-empty").hover((function() {
      $(this).removeClass("icon-calendar-empty");
      return $(this).addClass("icon-play-circle");
    }), function() {
      $(this).removeClass("icon-play-circle");
      return $(this).addClass("icon-calendar-empty");
    });


    $("#new_mail").validate({
      wrapper: "span",
      errorElement: 'div',
      errorClass: 'label',
      rules: {
        "mail[mail]": {
          required: true,
          email: true
        }
      },
      messages: {
        "mail[mail]": {
          required: "Introduza um email para receber novidades",
          email: "O seu email não é válido!"
        }
      },
      errorPlacement: function(error, element) {
        console.log(element.next());
        error.insertAfter(element.next());
      },
      highlight: function(element) {
        $(element).closest('.form-control').removeClass('success').addClass('error');
      },
      success: function(element) {
        element.addClass('valid').closest('.form-control').removeClass('error').addClass('success');
      }
    });
    $(".frame").fancybox({
      tpl: {
        closeBtn: '<a title="Close" class="fancybox-item fancybox-close myClose" href="javascript:;"></a>'
      },
      maxWidth  : 800,
      maxHeight : 600,
      fitToView : false,
      width   : '70%',
      height    : '70%',
      autoSize  : false,
      closeClick  : false,
      openEffect  : 'none',
      closeEffect : 'none',
      padding: 0,
      modal: false,
      helpers: {
        overlay: {
          locked: false
        }
      }
    });
    $('a[href*=#]:not([href=#])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
      || location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 1000);
          return false;
        }
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AgroSocial</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
</head>
<body>
	<% unless flash.empty? %>
		<% flash.each do |key, value| %>
			<script type="text/javascript">
				var jacked = humane.create({
					baseCls: 'humane-jackedup',
					addnCls: 'humane-jackedup-success',
					timeout: 5000
				})
				jacked.log("<%= value %>")
			</script>
		<% end %>
	<% end %>
	<%= yield %>
</body>
</html>